### ISSUE TITLE
Simple Polygon

### ISSUE THREAD

**Issue by KaitaniLabs** [gamelab/Primitives-Plugin#12]
First off, love KiwiJS, thank you so much for providing this great framework, and the Primitives plugin is extremely useful.

I'm trying to understand how best to draw a simple polygon. I have an array of points ([[x,y],[x,y]]), that works perfectly for a Line primitive as an outline, but I need to be able to click on the middle of the outlined area to select it. I have experience with SVG so my mind defaults to a polygon.

I'm new to all of this, and so I'm a bit baffled by the indices, strokeIndices, vertices concept. How best to use my array of points to achieve a clickable polygon? The array of points is dynamically created, not hard-coded.

The usage is for a tile-based strategy game. The polygons represent provinces on a map. Each one has a different shape. Attached is a screenshot of the current working version using the Line primitive.

![screen shot 2016-10-25 at 10 27 32](https://cloud.githubusercontent.com/assets/5583346/19682021/9f67df8e-9aa3-11e6-98ae-825c19ab0e95.png)

Any thoughts on best way to go about this? Thanks.

**Comment by BenjaminDRichards** [comment]
A great question, and one I wish I had a complete answer to!

As you can imagine, it's a little tricky to figure out how to actually construct a complicated polygon from triangles. The SVG spec will do this automatically, which is great. But Primitives was never intended to do SVG-style complex graphics. The strength of Primitives is in putting very simple geometry objects to the screen as efficiently as possible.

The Polygon object can construct more complex objects, but it does so in a fairly constrained way, to preserve this simplicity and efficiency. Put simply, it draws a series of triangles, each of which must share a side with the previous triangle. With one extra trick, this can theoretically draw any shape. That trick is the "degenerate triangle", which has two points in the same place and thus no visible area; degenerate triangles can "shortcut" the triangles to another location without visible connections.

However, there are two reasons why that's not a good solution here. First, it still requires a lot of calculation to figure out what those triangles should be, and I couldn't say what those calculations actually are without a lot of work. Second, KiwiJS hitboxes are AABB: nothing more than a box on the screen, containing the object and also some other space. Hitboxes wouldn't be the right way to find what the user clicked.

Looking at your screenshot, I can see an underlying grid. That forms a much more efficient solution in my mind. If you can store the province of each grid square, then do a grid lookup on mousedown, you can very efficiently find the correct location. This should have only a nominal memory cost. In addition, it should be very performant. Hitbox calculations necessarily check against all the hitboxes in the scene, which is very inefficient. In a grid, you can immediately calculate the correct cell purely from pointer/camera coordinates. (Don't forget to use `transformPoint()` on the camera to get the world coordinates of the pointer!)

That should give you perfectly accurate province selection and high performance.

Of course, this only works if you use an underlying grid. If you move to provinces with totally freeform borders, things change. You can still use the grid, but it will be a little inaccurate around borders. You could use Voronoi cells, which I think should always be convex and thus fairly easy to construct from triangles. Or you could use `Polygon.combine()` on several shapes to turn them into one polygon; this could be useful for creating province highlights even in the current scheme. Beware; combined shapes might not be very efficient, so you'll want to hide or destroy them when not in use.

Hope this helps, and I'm very interested in the outcome. That's an interesting map.

**Comment by KaitaniLabs** [comment]
Hi Ben, thanks for the reply. In the end I went for a simple solution which was to apply a textField for each province to show its name and add an input on it to select the province. Nice and simple.

Grid squares are tagged to the province so if things become more complex that's always an option. 

Thanks again for the reply :)
